DOCS UPDATE: Add additional notes on name resolution of structs
COVESA/vehicle_signal_specification pull request #560
Opened 2023-03-01 20:08 UTC by kkoppolu1

## Notes
Add notes on name resolution in struct documentation 

## Testing
Tested on local hugo server.
Screenshot:   

![docs](https://user-images.githubusercontent.com/71738025/222254053-29710355-6bbc-4717-9209-d7e2171219f5.png)

2023-03-02 13:14 UTC, erikbosch requested changes
Minor spelling error, when fixed good to go as I see it. 

(As it concerns document change only I see no need for an urgent merge, but on the other hand no reason to wait +1 week. Possibly direct merge decision on Tuesday?)

2023-03-02 13:14 UTC, erikbosch commented on docs-gen/content/rule_set/data_entry/data_types_struct.md
> +* Reference by absoulte path
Minor spelling error "absoulte"

2023-03-02 16:54 UTC, kkoppolu1 commented
Corrected the spelling error. Can bring this up during the Tuesday session.

2023-03-03 12:24 UTC, erikbosch approved these changes

2023-03-06 08:12 UTC, merged