Update allowed.md
COVESA/vehicle_signal_specification pull request #565
Opened 2023-03-17 19:43 UTC by neil-rti

Improve clarity of example by introducing a value that is easily recognized as not belonging in the 'allowed' list.

2023-03-20 14:56 UTC, erikbosch requested changes
Looks ok, but the "signed-off" in the commit (required according to https://www.covesa.global/contribute) seems to be missing

2023-03-24 04:23 UTC, neil-rti commented
Signed-off-by: Neil Puthuff <neil@rti.com>

2023-03-27 11:36 UTC, erikbosch commented
Sign-off briefly discussed in data expert group. Opinion seems to be that sign-off should be on commit. @neil-rti  - if you do a git `commit -s --amend` to add sign off and then a force push then it should be ready for merge

2023-03-28 14:26 UTC, erikbosch commented
Meeting notes: Ready to merge

2023-03-29 10:44 UTC, merged